#äº‘ç¼–è¯‘å…¬ç”¨æ ¸å¿ƒ
name: ã€è”åˆç¼–è¯‘å…¬ç”¨æ ¸å¿ƒã€‘

on:
  #å…¬ç”¨æ ¸å¿ƒæ ‡è¯†
  workflow_call:
    inputs:
      CORE_TARGET:
        required: true
        type: string
      CORE_THEME:
        required: true
        type: string
      CORE_NAME:
        required: true
        type: string
      CORE_URL:
        required: true
        type: string
      CORE_PW:
        required: true
        type: string
      CORE_IP:
        required: true
        type: string
      CORE_BRANCH:
        required: true
        type: string
      CORE_tag_name:
        required: true
        type: string
      CORE_header:
        required: true
        type: string
      CORE_config:
        required: true
        type: string
      CORE_patch:
        required: true
        type: string
      CORE_patch_after:
        required: true
        type: string
      CORE_SOC_P1_SH:
        required: true
        type: string
      CORE_SOC_P2_SH:
        required: true
        type: string
      CORE_DIY_P1_SH:
        required: true
        type: string
      CORE_DIY_P2_SH:
        required: true
        type: string
      CORE_DIY_P3_SH:
        required: true
        type: string
      CORE_DIY_P4_SH:
        required: true
        type: string
      CORE_remove:
        required: true
        type: string
      CORE_LINUX:
        required: true
        type: string
      CORE_FILES:
        required: true
        type: string
      kernel_repo:
        required: true
        type: string
      kernel_usage:
        required: true
        type: string
      builder_name:
        required: true
        type: string
      auto_kernel:
        required: true
        type: string
      CORE_Pack:
        required: true
        type: string
      CORE_feeds_conf:
        required: true
        type: string
      CORE_META:
        required: true
        type: string
      CORE_Files_SH:
        required: true
        type: string
      OP_router:
        required: true
        type: string
env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  CORE_TARGET: ${{inputs.CORE_TARGET}}
  CORE_THEME: ${{inputs.CORE_THEME}}
  CORE_NAME: ${{inputs.CORE_NAME}}
  CORE_URL: ${{inputs.CORE_URL}}
  CORE_PW: ${{inputs.CORE_PW}}
  CORE_IP: ${{inputs.CORE_IP}}
  CORE_BRANCH: ${{inputs.CORE_BRANCH}}
  CORE_tag_name: ${{inputs.CORE_tag_name}}
  CORE_header: header/${{inputs.CORE_header}}
  CORE_config: Config/${{inputs.CORE_config}}
  CORE_patch: patch/${{inputs.CORE_patch}}
  CORE_patch_after: patch/${{inputs.CORE_patch_after}}
  CORE_SOC_P1_SH: soc/${{inputs.CORE_SOC_P1_SH}}
  CORE_SOC_P2_SH: soc/${{inputs.CORE_SOC_P2_SH}}
  CORE_DIY_P1_SH: Scripts/${{inputs.CORE_DIY_P1_SH}}
  CORE_DIY_P2_SH: Scripts/${{inputs.CORE_DIY_P2_SH}}
  CORE_DIY_P3_SH: Scripts/${{inputs.CORE_DIY_P3_SH}}
  CORE_DIY_P4_SH: Scripts/${{inputs.CORE_DIY_P4_SH}}
  CORE_remove: remove/${{inputs.CORE_remove}}
  CORE_LINUX: ${{inputs.CORE_LINUX}}
  CORE_FILES: patch/${{inputs.CORE_FILES}}
  kernel_repo: ${{inputs.kernel_repo}}
  kernel_usage: ${{inputs.kernel_usage}}
  builder_name: ${{inputs.builder_name}}
  auto_kernel: ${{inputs.auto_kernel}}
  CORE_Pack: ${{inputs.CORE_Pack}}
  CORE_feeds_conf: patch/${{inputs.CORE_feeds_conf}}
  CORE_META: ${{inputs.CORE_META}}
  CORE_Files_SH: remove/${{inputs.CORE_Files_SH}}
  OP_router: ${{inputs.OP_router}}
  TZ: Asia/Shanghai

jobs:
  union_core:
    runs-on: ubuntu-latest
    steps:
      - name: æ¸…ç†æœåŠ¡å™¨ç©ºé—´(Ubuntu)
        uses: rmoyulong/free-disk-space@main
        with:
          # this might remove tools that are actually needed,
          # if set to "true" but frees about 6 GB
          tool-cache: true

          # all of these default to true, but feel free to set to
          # "false" if necessary for your workflow
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true
        
      - name: é¡¹ç›®æ£€æŸ¥
        uses: actions/checkout@main

      - name: æœ€å¤§åŒ–ç¼–è¯‘ç©ºé—´
        uses: rmoyulong/maximize-build-space@master
        with:
          root-reserve-mb: 2048
          swap-size-mb: 1024
          build-mount-path: /workdir
          overprovision-lvm: 'true'
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'

      - name: æ£€æŸ¥åˆ†é…çš„æœåŠ¡å™¨æ€§èƒ½
        run: |
          echo "è­¦å‘Šâš "
          echo "åˆ†é…çš„æœåŠ¡å™¨æ€§èƒ½æœ‰é™ï¼Œè‹¥é€‰æ‹©çš„æ’ä»¶è¿‡å¤šï¼ŒåŠ¡å¿…æ³¨æ„CPUæ€§èƒ½ï¼"
          echo -e "å·²çŸ¥CPUå‹å·ï¼ˆé™åºï¼‰ï¼š7763ï¼Œ8370Cï¼Œ8272CLï¼Œ8171Mï¼ŒE5-2673 \n"
          echo "--------------------------CPUä¿¡æ¯--------------------------"
          echo "CPUç‰©ç†æ•°é‡ï¼š$(cat /proc/cpuinfo | grep "physical id" | sort | uniq | wc -l)"
          echo -e "CPUæ ¸å¿ƒä¿¡æ¯ï¼š$(cat /proc/cpuinfo | grep name | cut -f2 -d: | uniq -c) \n"
          echo "--------------------------å†…å­˜ä¿¡æ¯--------------------------"
          echo "å·²å®‰è£…å†…å­˜è¯¦ç»†ä¿¡æ¯ï¼š"
          echo -e "$(sudo lshw -short -C memory | grep GiB) \n"
          echo "--------------------------ç¡¬ç›˜ä¿¡æ¯--------------------------"
          echo "ç¡¬ç›˜æ•°é‡ï¼š$(ls /dev/sd* | grep -v [1-9] | wc -l)" && df -hT   

      - name: åˆå§‹åŒ–ç¼–è¯‘ç¯å¢ƒ
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo -E apt-get -qq update --fix-missing
          sudo -E apt-get -qq full-upgrade
          sudo -E apt-get -y install $(cat $GITHUB_WORKSPACE/Ubuntu-2204.txt)
          sudo -E apt-get -qq autoremove --purge
          sudo -E apt-get -qq clean
          sudo -E systemctl daemon-reload
          sudo timedatectl set-timezone "$TZ"
          sudo mkdir -p /workdir
          sudo chown $USER:$GROUPS /workdir
          echo "status=success" >> ${GITHUB_OUTPUT}
          df -Th              

      - name: åˆå§‹åŒ–å˜é‡
        run: |
          export CORE_DATE=$(TZ=UTC-8 date +"%y.%m.%d_%H.%M.%S")
          export CORE_SOURCE=$(echo $CORE_URL | cut -d '/' -f 5-)
          
          echo "CORE_SOURCE=$CORE_SOURCE" >> $GITHUB_ENV
          echo "CORE_TARGET=$CORE_TARGET" >> $GITHUB_ENV
          echo "CORE_DATE=$CORE_DATE" >> $GITHUB_ENV
          echo "CORE_PW=$CORE_PW" >> $GITHUB_ENV
          echo "CORE_IP=$CORE_IP" >> $GITHUB_ENV
          echo "CORE_BRANCH=$CORE_BRANCH" >> $GITHUB_ENV
          echo "CORE_tag_name=$CORE_tag_name" >> $GITHUB_ENV
          echo "CORE_header=$CORE_header" >> $GITHUB_ENV
          echo "CORE_config=$CORE_config" >> $GITHUB_ENV
          echo "CORE_patch=$CORE_patch" >> $GITHUB_ENV
          echo "CORE_patch_after=$CORE_patch_after" >> $GITHUB_ENV
          echo "CORE_SOC_P1_SH=$CORE_SOC_P1_SH" >> $GITHUB_ENV
          echo "CORE_SOC_P2_SH=$CORE_SOC_P2_SH" >> $GITHUB_ENV
          echo "CORE_DIY_P1_SH=$CORE_DIY_P1_SH" >> $GITHUB_ENV
          echo "CORE_DIY_P2_SH=$CORE_DIY_P2_SH" >> $GITHUB_ENV
          echo "CORE_DIY_P3_SH=$CORE_DIY_P3_SH" >> $GITHUB_ENV
          echo "CORE_DIY_P4_SH=$CORE_DIY_P4_SH" >> $GITHUB_ENV
          echo "CORE_remove=$CORE_remove" >> $GITHUB_ENV
          echo "CORE_LINUX=$CORE_LINUX" >> $GITHUB_ENV
          echo "CORE_FILES=$CORE_FILES" >> $GITHUB_ENV
          echo "kernel_repo=$kernel_repo" >> $GITHUB_ENV
          echo "kernel_usage=$kernel_usage" >> $GITHUB_ENV
          echo "builder_name=$builder_name" >> $GITHUB_ENV
          echo "auto_kernel=$auto_kernel" >> $GITHUB_ENV
          echo "CORE_Pack=$CORE_Pack" >> $GITHUB_ENV
          echo "CORE_feeds_conf=$CORE_feeds_conf" >> $GITHUB_ENV
          echo "CORE_THEME=$CORE_THEME" >> $GITHUB_ENV
          echo "CORE_META=$CORE_META" >> $GITHUB_ENV
          echo "CORE_Files_SH=$CORE_Files_SH" >> $GITHUB_ENV
          echo "OP_router=$OP_router" >> $GITHUB_ENV
          
          echo "CORE_META: $CORE_META"
          echo "CORE_IP: $CORE_IP"
          echo "CORE_THEME: $CORE_THEME"
          echo "OP_router: $OP_router"
          
          # ä½¿ç”¨æ­£åˆ™è¡¨è¾¾å¼æ ¡éªŒIPåœ°å€æ ¼å¼æ˜¯å¦ç¬¦åˆè§„èŒƒ
          if [[ $CORE_IP =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "IPåœ°å€ $CORE_IP ç¬¦åˆè§„èŒƒã€‚"
          else
            echo "IPåœ°å€ $CORE_IP ä¸ç¬¦åˆè§„èŒƒã€‚"
            exit 1
          fi
  
      - name: æ£€æŸ¥è„šæœ¬
        run: |
          dos2unix ./Scripts/*.sh
          chmod +x ./Scripts/*.sh
          
          dos2unix ./soc/*.sh
          chmod +x ./soc/*.sh
          
          dos2unix ./patch/*.sh
          chmod +x ./patch/*.sh
          
          dos2unix ./remove/*.sh
          chmod +x ./remove/*.sh
          

      - name: å…‹éš†æºç åº“
        id: codes
        working-directory: /workdir        
        run: |
          # Set up compilation source code
          if [[ "${{ inputs.CORE_URL }}" == *"openwrt/openwrt"* ]]; then
              REPO_URL="https://github.com/openwrt/openwrt"
              REPO_BRANCH="main"
          elif [[ "${{ inputs.CORE_URL }}" == *"coolsnowwolf/lede"* ]]; then
              REPO_URL="https://github.com/coolsnowwolf/lede"
              REPO_BRANCH="master"
          elif [[ "${{ inputs.CORE_URL }}" == *"immortalwrt/immortalwrt"* ]]; then
              REPO_URL="https://github.com/immortalwrt/immortalwrt"
              REPO_BRANCH="master"
          else
              REPO_URL="${{ inputs.CORE_URL }}"
              REPO_BRANCH="${{ inputs.CORE_BRANCH }}"
          fi
          
          if [[ $CORE_LINUX == *"5.15"* ]] ; then
              REPO_URL="${{ inputs.CORE_URL }}"
              REPO_BRANCH="${{ inputs.CORE_BRANCH }}"
          fi
          
          df -hT $PWD
          git clone -q --single-branch --depth=1 --branch=${REPO_BRANCH} ${REPO_URL} openwrt
          ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt
  
      - name: åŠ è½½è‡ªå®šä¹‰è®¢é˜…æº
        run: |
          cd openwrt
          
          if [[ "${{ inputs.CORE_feeds_conf }}" == *"false"* ]]; then
            echo "ä½¿ç”¨é»˜è®¤feeds.conf.defaultæ–‡ä»¶"
          else
            cp -rf $GITHUB_WORKSPACE/${{ env.CORE_feeds_conf }} ./feeds.conf.default
          fi
          
          if [[ "${{ inputs.CORE_DIY_P1_SH }}" == *"false"* ]]; then
            echo "ä¸éœ€è¦æ‰§è¡Œ CORE_DIY_P1_SH"
          else
            ${GITHUB_WORKSPACE}/${CORE_DIY_P1_SH}
          fi          
          echo "COMMIT_HASH=$(git rev-parse HEAD)" >> $GITHUB_ENV
          
      - name: å‰ç½®è¡¥ä¸
        run: |
          if [[ "${{ inputs.CORE_patch }}" == *"false"* ]]; then
            echo "ä¸éœ€è¦æ‰“å‰ç½®è¡¥ä¸"
          else
            ${GITHUB_WORKSPACE}/${CORE_patch}
          fi

      - name: å¯åŠ¨ç¼“å­˜[ç¬¬äºŒæ¬¡èµ·ç”Ÿæ•ˆ]
        uses: rmoyulong/cachewrtbuild@main
        with:
          ccache: 'true'
          prefix: ${{ github.workspace }}/openwrt
          mixkey: ${{ env.CORE_SOURCE }}/tree/${{ env.CORE_TARGET }}?device=${{ env.CORE_header }}-${{ env.CORE_config }}
          
      - name: æ›´æ–°è®¢é˜…æº
        run: |
          cd openwrt
          
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          
      - name: åç½®è¡¥ä¸
        run: |
          if [[ "${{ inputs.CORE_patch_after }}" == *"false"* ]]; then
            echo "ä¸éœ€è¦æ‰“åç½®è¡¥ä¸"
          else
            ${GITHUB_WORKSPACE}/${CORE_patch_after}
          fi
         
      - name: é€šç”¨è„šæœ¬
        run: |
          cd openwrt
          
          curl -L -o package/base-files/files/etc/banner https://raw.githubusercontent.com/rmoyulong/AX6-Actions_Lede/master/ax6/cats_banner
          ${GITHUB_WORKSPACE}/${CORE_DIY_P2_SH} "${{ env.CORE_IP }}" "${{ env.CORE_NAME }}" "${{ env.CORE_THEME }}" "${{ env.CORE_SOURCE }}"
          
          if [[ "${{ inputs.CORE_DIY_P3_SH }}" == *"false"* ]]; then
            echo "ä¸éœ€è¦æ‰§è¡Œ CORE_DIY_P3_SH"
          else
            ${GITHUB_WORKSPACE}/${CORE_DIY_P3_SH} "${CORE_FILES}" "${CORE_header}" "${{ env.CORE_SOURCE }}"
          fi
          
          if [[ "${{ inputs.CORE_DIY_P4_SH }}" == *"false"* ]]; then
            echo "ä¸éœ€è¦æ‰§è¡Œ CORE_DIY_P4_SH"
          else
            ${GITHUB_WORKSPACE}/${CORE_DIY_P4_SH} "${{ inputs.CORE_META }}" "${{ inputs.CORE_IP }}"
          fi 

      - name: åˆ é™¤å†²çªçš„æ’ä»¶
        run: |
          cd openwrt
          
          if [[ "${{ inputs.CORE_remove }}" == *"false"* ]]; then
            echo "ä¸éœ€è¦åˆ é™¤å†²çªçš„æ’ä»¶"
          else
            ${GITHUB_WORKSPACE}/${CORE_remove}
          fi
          
      - name: æ‹·è´ç¼–è¯‘é…ç½®æ–‡ä»¶å’Œæ’ä»¶åˆå§‹åŒ–æ–‡ä»¶
        run: |
          cd openwrt
          
          #å¦‚æœfilesæ–‡ä»¶å¤¹ä¸å­˜åœ¨ï¼Œåˆ›å»ºæ–‡ä»¶å¤¹
          if [ ! -d "./files" ]; then
            mkdir ./files
          fi
          [ -e $GITHUB_WORKSPACE/$CORE_FILES ] && cp -rf $GITHUB_WORKSPACE/$CORE_FILES/* ./files
          
          rm -rf ./tmp* ./.config*
          rm -rf ./.config
          
          if [[ "${{ inputs.CORE_header }}" == *"false"* ]]; then
             echo "æ²¡æœ‰header configæ–‡ä»¶"
             cat ${GITHUB_WORKSPACE}/${CORE_config}  > .config
          else
             cat $GITHUB_WORKSPACE/${CORE_header}  > .config
             cat $GITHUB_WORKSPACE/${CORE_config} >> .config
          fi
          #cat .config          

      - name: ä¿®æ­£filesæ–‡ä»¶é…ç½®
        run: |
          cd openwrt
          
          if [[ "${{ inputs.CORE_Files_SH }}" == *"false"* ]]; then
            echo "ä¸éœ€è¦æ‰§è¡Œ CORE_Files_SH"
          else
            ${GITHUB_WORKSPACE}/${CORE_Files_SH} "$OP_router" "$CORE_NAME" "${{ inputs.CORE_IP }}"
            echo $OP_router
            echo $CORE_header
          fi
          
      - name: ä¸‹è½½ç¼–è¯‘ä¾èµ–
        working-directory: ./openwrt
        run: |
          make defconfig
          make download -j$(nproc)
          #make download -j8
          #make -j16 download
          find dl -size -1024c -exec ls -l {} \;
          find dl -size -1024c -exec rm -f {} \;

      - name: ç¼–è¯‘å›ºä»¶
        working-directory: ./openwrt
        run: |     
          echo -e "$(nproc) thread compile"
          make -j$(nproc) || make -j1 || make -j1 V=s
          echo "status=success" >> $GITHUB_OUTPUT
          echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV 
 
      - name: å›ºä»¶å•ç‹¬å¤„ç†è„šæœ¬
        run: |
          if [[ "${{ inputs.CORE_SOC_P1_SH }}" == *"false"* ]]; then
            echo "æ²¡æœ‰éœ€è¦å•ç‹¬å¤„ç†çš„è„šæœ¬1"
          else
            ${GITHUB_WORKSPACE}/${CORE_SOC_P1_SH}
          fi
          
          if [[ "${{ inputs.CORE_SOC_P2_SH }}" == *"false"* ]]; then
            echo "æ²¡æœ‰éœ€è¦å•ç‹¬å¤„ç†çš„è„šæœ¬2"
          else
            ${GITHUB_WORKSPACE}/${CORE_SOC_P2_SH}
          fi
          
      - name: è·å¾—å›ºä»¶ä¿¡æ¯
        run: |
          cd openwrt/bin/targets/*/*
          kword=$(cat *.manifest | grep ^kernel | cut -d- -f2 | tr -d ' ')
          KERNEL=${kword%~*}
          echo "KERNEL=$KERNEL" >> $GITHUB_ENV
          cat sha256sums
          
      - name: æ•´ç†å›ºä»¶
        run: |
          cd openwrt && mkdir ./upload
          
          rm -rf $(find ./bin/targets/ -iregex ".*\(json\|manifest\|buildinfo\|sha256sums\|packages\)$")
          cp -rf $(find ./bin/targets/ -type f -iname "*.*") ./upload/
          cp -rf ./.config ./upload/Config.txt
          
          export CORE_DATE=$(TZ=UTC-8 date +"%y.%m.%d_%H.%M.%S")
          echo "CORE_DATE=$CORE_DATE" >> $GITHUB_ENV
          show_tag_name=${{env.CORE_TARGET}}_${{env.CORE_SOURCE}}_${{env.CORE_DATE}}
          echo "show_tag_name=$show_tag_name" >> $GITHUB_ENV
          #è·å¾—å½“å‰ç›®å½•çš„è·¯å¾„ä¿¡æ¯
          cd ./upload
          echo "FIRMWARE=$PWD" >> $GITHUB_ENV
          
          #å¦‚æœ‰.taræ–‡ä»¶å°±è½¬åŒ–ä¸º.gz
          files=$(ls *.tar 2> /dev/null | wc -l)
          if [ "$files" != "0" ]; then
            gzip *.tar
          fi

      - name: Armv8æ‰“åŒ…OpenWrt
        if: env.CORE_Pack == 'ophub'
        uses: ophub/amlogic-s9xxx-openwrt@main
        with:
          openwrt_path: openwrt/upload/*rootfs.tar.gz
          openwrt_board: ${{ env.CORE_TARGET }}
          openwrt_kernel: ${{ env.CORE_LINUX }}
          auto_kernel: ${{ inputs.auto_kernel }}
          kernel_repo: ${{ inputs.kernel_repo }}
          kernel_usage: ${{ inputs.kernel_usage }}
          builder_name: ${{ inputs.builder_name }}

      - name: å°†ç¼–è¯‘çš„åº•åŒ…è½¬æ¢ä¸ºOpenWrt
        if: env.CORE_Pack == 'flippy'
        uses: ophub/flippy-openwrt-actions@main
        env:
          OPENWRT_ARMVIRT: openwrt/upload/*rootfs.tar.gz
          PACKAGE_SOC: ${{ env.CORE_TARGET }}
          WHOAMI: moyulong
          KERNEL_VERSION_NAME: ${{ env.CORE_LINUX }}
          KERNEL_AUTO_LATEST: true
          GZIP_IMGS: .gz
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: åˆå¹¶åŸå§‹èµ„æ–™å’Œæ‰“åŒ…æ–‡ä»¶
        if: env.CORE_Pack == 'ophub'  ||  env.CORE_Pack == 'flippy'
        run: |
          cp -f openwrt/upload/*.* ${{ env.PACKAGED_OUTPUTPATH }}/
          cd ${{ env.PACKAGED_OUTPUTPATH }}/
          echo "FIRMWARE=$PWD" >> $GITHUB_ENV
          
      - name: ç”Ÿæˆæ ‡ç­¾ï¼Œä¸Šä¼ å›ºä»¶
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{env.show_tag_name}}
          body: |
            ====================ğŸ§Šå›ºä»¶ä¿¡æ¯ğŸ§Š=======================
            â¦ ğŸ“’ å›ºä»¶åç§°ï¼š${{env.CORE_NAME}} ${{env.CORE_tag_name}}
            â¦ ğŸ’» å›ºä»¶å¹³å°ï¼š${{ env.CORE_TARGET }}
            â¦ âš½ å›ºä»¶æºç ï¼š${{ env.CORE_SOURCE }}
            â¦ ğŸ’ æºç åˆ†æ”¯ï¼š${{ env.CORE_BRANCH }}
            â¦ ğŸš€ å†…æ ¸ç‰ˆæœ¬ï¼š${{ env.KERNEL }}
            â¦ ğŸŒ é»˜è®¤åœ°å€ï¼š${{env.CORE_IP}}
            â¦ ğŸ”‘ é»˜è®¤å¯†ç ï¼špassword            
          artifacts: ${{ env.FIRMWARE }}/*
          
      - name: æ¸…ç†Releases
        uses: rmoyulong/delete-older-releases@master
        with:
          keep_latest: 16
          delete_tags: true

      - name: æ¸…ç†Workflows
        uses: rmoyulong/delete-workflow-runs@main
        with:
          retain_days: 0
          keep_minimum_runs: 1
